name: DemocracyYutnori
version: ${project.version}
main: yasking.lupi13.democracyyutnori.DemocracyYutnori
api-version: 1.17
authors: [ LuPi13 ]
description: 140percent democratic Yut-Nori
website: https://github.com/LuPi13
commands:
  yut:
    description: Starts Yut-Nori
    usage: /<command>